export const ROLENAMES = {
  SUPERADMIN: "SUPERADMIN",
  ADMINPANEL: "ADMINPANEL",
  HR: "HR",
  REGISTEREDUSER: "REGISTEREDUSER",
  HEADFORPERMISSION: "HEADFORPERMISSION",
  TEAMLEAD: "TEAMLEAD",
  PM: "PM",
  ROLES: {
    SIDEBAR_MANAGMENT: {
      HUMANR: "HUMANR_READ",
      SETTINGS: "SETTINGS_READ",
    },
    USER_LIST: {
      READ: "USM_READ",
      CREATE: "USM_CREATE",
      EDIT: "USM_EDIT",
      DELETE: "USM_DELETE",
      DESCRIPTION: "User List Role names ",
    },
    LANGUAGE_LIST: {
      READ: "LANG_READ",
      CREATE: "LANG_CREATE",
      EDIT: "LANG_EDIT",
      DELETE: "LANG_DELETE",
      DESCRIPTION: "Language list Role names ",
    },
    ROLE_LIST: {
      READ: "ROM_READ",
      CREATE: "ROM_CREATE",
      EDIT: "ROM_EDIT",
      DELETE: "ROM_DELETE",
      DESCRIPTION: "Role list Role names ",
    },
    ROLEGROUP_LIST: {
      READ: "ROGM_READ",
      CREATE: "ROGM_CREATE",
      EDIT: "ROGM_EDIT",
      DELETE: "ROGM_DELETE",
      DESCRIPTION: "Role Group list Role names ",
    },
    CURRENCY: {
      READ: "CUR_READ",
      CREATE: "CUR_CREATE",
      EDIT: "CUR_EDIT",
      DELETE: "CUR_DELETE",
      DESCRIPTION: "CURRENCY list Role Names",
    },
    PERMISSION: {
      READ: "PER_READ",
      CREATE: "PER_CREATE",
      EDIT: "PER_EDIT",
      DELETE: "PER_DELETE",
      DESCRIPTION: "PERMISSION list Role Names",
    },
    ADMPERMISSION: {
      READ: "ADMPER_READ",
      CREATE: "ADMPER_CREATE",
      EDIT: "ADMPER_EDIT",
      DELETE: "ADMPER_DELETE",
      DESCRIPTION: "Admin PERMISSION list Role Names",
    },
    LANGUAGE_RESOURCES: {
      READ: "LARE_READ",
      CREATE: "LARE_CREATE",
      EDIT: "LARE_EDIT",
      DELETE: "LARE_DELETE",
      DESCRIPTION: "RESOURCE list Role Names",
    },
    EMPLOYEES: {
      READ: "EMP_READ",
      CREATE: "EMP_CREATE",
      EDIT: "EMP_EDIT",
      DELETE: "EMP_DELETE",
      DESCRIPTION: "Employees Role names ",
    },
    EMPLOYEE_SALARIES: {
      READ: "EMPS_READ",
      CREATE: "EMPS_CREATE",
      EDIT: "EMPS_EDIT",
      DELETE: "EMPS_DELETE",
      DESCRIPTION: "Employee Salaries Role names ",
    },
    EMPLOYEE_POSITIONS: {
      READ: "EMPP_READ",
      CREATE: "EMPP_CREATE",
      EDIT: "EMPP_EDIT",
      DELETE: "EMPP_DELETE",
      DESCRIPTION: "Employee Positions Role names ",
    },
    CITIES: {
      READ: "CT_READ",
      CREATE: "CT_CREATE",
      EDIT: "CT_EDIT",
      DELETE: "CT_DELETE",
      DESCRIPTION: "Cities Role names ",
    },
    SALARY_REPORT_LIST: {
      READ: "SR_READ",
      CREATE: "SR_CREATE",
      EDIT: "SR_EDIT",
      DELETE: "SR_DELETE",
      DESCRIPTION: "Salary Report list Role names ",
    },
    DEPARTMENTS: {
      READ: "DP_READ",
      CREATE: "DP_CREATE",
      EDIT: "DP_EDIT",
      DELETE: "DP_DELETE",
      DESCRIPTION: "Department list Role names ",
    },
    TEAM_MEMBERS: {
      READ: "TM_READ",
      CREATE: "TM_CREATE",
      EDIT: "TM_EDIT",
      DELETE: "TM_DELETE",
      DESCRIPTION: "Team Members Role names ",
    },
  },
};

export default ROLENAMES;
